name: test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: fetch-repo[checkout]
      uses: actions/checkout@v3
    - name: check the repo
      run: ls -la